# vim: set foldmethod=marker:
# General {{{
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias :q='clear; exit'
alias cl='clear'
alias df='df -h'
alias di='colordiff'
alias du='du -c -h'
alias grep='grep --color=auto'
alias l='ls -lh'
alias la='ls -lha'
alias ls='ls --hyperlink=auto --color=auto'
alias lsa='ls -a'
alias m='mutt -F ~/.config/mutt/muttrc'
alias y='yazi'
alias sudo='sudo '
alias svi='sudo -e'
alias ta='tmux attach'
alias va='source .venv/bin/activate'
alias vi='nvim'
# }}}
# Linux {{{
alias log='journalctl -r'
alias sc='sudo systemctl'
alias scu='systemctl --user'
alias jc='journalctl'
# pacman
alias pac='pacman '
alias pacr='sudo pacman -Rs'
# }}}
# git {{{
alias g='git '
alias gb='git branch'
alias gco='git commit'
alias gd='git diff'
alias gf='git fetch --all -p'
alias gfu='git commit -a --fixup=HEAD'
alias gdw='git diff --color-words'
alias gl='git log --pretty=format:"%C(yellow)%h%Cred%d %Creset%s%Cblue [%an]" --graph -20'
alias glo='git log --pretty=format:"%C(yellow)%h%Cred%d %Creset%s%Cblue [%an]" --graph'
alias gpl='git pull'
alias gpu='git push'
alias gr='git rebase'
alias gri='git rebase -i'
alias gs='git status'
alias go='git checkout'
# }}}
