#!/bin/bash

brew install --HEAD --with-opusfile cmus
brew install --with-bundle mpv
brew install --HEAD universal-ctags

brew install \
    borgbackup \
    colordiff \
    coreutils \
    curl \
    exiftool \
    findutils \
    fzf \
    git \
    gnupg \
    gnutls \
    imagemagick \
    isync \
    khal \
    lynx \
    mercurial \
    msmtp \
    mutt \
    neovim \
    ninja \
    node \
    ntfs-3g \
    openssh \
    perl \
    python \
    python3 \
    ranger \
    ripgrep \
    rsync \
    shellcheck \
    sshfs \
    syncthing \
    the_silver_searcher \
    tmux \
    tree \
    urlview \
    wget \
