# aliases
alias ....='cd ../../..'
alias ...='cd ../..'
alias ..='cd ..'
alias :q='clear; exit'
alias cl='clear'
alias diff='colordiff'
alias du='du -c -h'
alias exit="clear; exit"
alias free='free -m'
alias grep='grep -n --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -a -l'
alias log='sudo journalctl -r'
alias ls='ls --color=auto'
alias svi='sudoedit'
alias vi='vim'
alias sudo='sudo '

# pacman
alias pac='sudo pacman'
alias pacclean='sudo pacman -Rs $(pacman -Qqtd)'
alias pacin='yaourt -S'
alias pacman='sudo pacman'
alias pacrm='pacman -Rs'
alias pacup='yaourt -Syu --aur'

# git
alias gitad='git add'
alias gitco='git commit'
alias gitdi='git diff --color-words'
alias gitig='vim .gitignore'
alias gitlo='git log --pretty=format:"%h %s" --graph -20'
alias gitpl='git pull'
alias gitpu='git push -u origin master'
alias gitrm='git rm'
alias gitst='git status'
