# Make sure XDG dirs are set
[[ -n "$XDG_CONFIG_HOME" ]] || export XDG_CONFIG_HOME=$HOME/.config
[[ -n "$XDG_CACHE_HOME"  ]] || export XDG_CACHE_HOME=$HOME/.cache
[[ -n "$XDG_DATA_HOME"   ]] || export XDG_DATA_HOME=$HOME/.local/share

export EDITOR="vim"
export HISTSIZE=2000
export HISTFILE="$XDG_CONFIG_HOME/zsh/history"
export SAVEHIST=$HISTSIZE
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export VIMDOTDIR="$XDG_CONFIG_HOME/vim"
export FRESH_RCFILE="$HOME/dev/dotfiles/freshrc"
export FRESH_PATH="$XDG_CONFIG_HOME/fresh"
export _Z_DATA="$XDG_CONFIG_HOME/zsh/z"
export LESSHISTFILE="$XDG_CONFIG_HOME/lesshst"
