export EDITOR="vim"
export HISTSIZE=2000
export HISTFILE="$HOME/.config/zsh/history"
export SAVEHIST=$HISTSIZE
[[ -z $XDG_CONFIG_HOME ]] && export XDG_CONFIG_HOME="$HOME/.config"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
export VIMDOTDIR="$XDG_CONFIG_HOME/vim"
