# initialise colors
autoload -U colors
colors

eval $(dircolors ~/.config/zsh/dircolors)

setopt PROMPT_SUBST

PROMPT='%n@%m %{$fg[green]%}%~>%{$reset_color%} '

# avoid duplicates in history
setopt hist_ignore_all_dups

# load private config
source ~/Documents/.localrc

# load some vars for fresh
source ~/.config/fresh/build/shell.sh

