# initialise colors
autoload -U colors
colors

eval $(dircolors ~/.config/zsh/dircolors)

setopt PROMPT_SUBST

PROMPT='%n@%m %{$fg[green]%}%~>%{$reset_color%} '

# avoid duplicates in history
setopt hist_ignore_all_dups

# load private config
if [ -f ~/Documents/.localrc ]
then
    source ~/Documents/.localrc
fi

# load some vars for fresh
source ~/.config/fresh/build/shell.sh

# use ag for fzf and ignore Library path on OS X
export FZF_DEFAULT_COMMAND="ag -l -g '' -p ~/.config/agignore"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
